[package]
name = "app"
version = "0.1.0"
authors = ["jay.xu <jay.xu@lenovonetapp.com>"]
description = "The application core code"
edition = "2024"

[features]
duckdb = ["db/duckdb"]
license = ["dep:licensing", "dep:chrono"]

[dependencies]
async-channel = { workspace = true }
async-trait   = { workspace = true }
blake3        = { workspace = true }
bytes         = { workspace = true }
chrono        = { workspace = true, optional = true }
dashmap       = { workspace = true }
db            = { workspace = true }
futures       = { workspace = true }
indicatif     = "0.18.4"
reqwest       = { workspace = true }
licensing     = { workspace = true, optional = true }
bincode       = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
tracing       = { workspace = true }
data-mover    = { workspace = true }
sync-delta    = { workspace = true }
thiserror     = { workspace = true }
tokio         = { workspace = true }
rustls        = { workspace = true }
transport     = { workspace = true, features = ["quic"] }
tokio-util    = { workspace = true, features = ["rt"] }
utils         = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
serial_test = "3.4.0"
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_Foundation",
] }
